export const ADD_INTERVIEW = 'ADD_INTERVIEW';
export const ADD_INTERVIEWS = 'ADD_INTERVIEWS';
export const UPDATE_INTERVIEW = 'UPDATE_INTERVIEW';
export const DELETE_INTERVIEW = 'DELETE_INTERVIEW';
export const DELETE_INTERVIEWS = 'DELETE_INTERVIEWS';
